name: Convert list to JSON

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  convert:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download list files
        id: download
        run: |
          if [ -f rules/list_sources.txt ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              # Skip empty lines and comments
              if [[ -z "$line" || "$line" =~ ^# ]]; then
                continue
              fi

              # Extract URL from "ruleset=...,URL" format or if the line is just a URL
              url=$(echo "$line" | awk -F, '{print $NF}')
              
              if [[ "$url" =~ ^https?:// ]]; then
                filename=$(basename "$url")
                curl -s -L -o "$filename" "$url"
                echo "Downloaded $filename from $url"
              fi
            done < rules/list_sources.txt
          else
            echo "rules/list_sources.txt not found."
          fi

      - name: Convert list to JSON
        run: |
          for list_file in *.list; do
            if [ -f "$list_file" ]; then
              echo "Processing $list_file..."
              python converter.py "$list_file"
            fi
          done

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add rules/
          git diff --staged --quiet || git commit -m "Update rules from list sources"
          git push